### Login user
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "james@nickjames.com",
    "password": "password"
}


### Get all Users
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2NTk2YmE1LWJlNzctNDljNy1iZjUwLWM3ZjkwNTJmZTA5MSIsImZuYW1lIjoiSmFtZXMiLCJvdGhlck5hbWVzIjoiS3VyaWEiLCJlbWFpbCI6ImphbWVzQG5pY2tqYW1lcy5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQzV1VPemhGeFdTeG5nY1NHd09qaVp1SncwSkFYNkYzNGtVWk9US3hUNGo4Nzc1LlZYTlJPSyIsImlhdCI6MTY2MjgxMjE0NCwiZXhwIjoxNjYyODEyMTc0fQ.dagmY8NlssYkCU7f0mPX4TM0ZWP9FhIGkocgGHeiOSA


### Generate new access token
POST http://localhost:5000/api/v1/auth/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoiYzYxYjRlZmQtMTZmOS00NjFhLWFiNGYtMWUwNjUwOGUxZTUxIiwidXNlciI6eyJpZCI6ImI2NTk2YmE1LWJlNzctNDljNy1iZjUwLWM3ZjkwNTJmZTA5MSIsImZuYW1lIjoiSmFtZXMiLCJvdGhlck5hbWVzIjoiS3VyaWEiLCJlbWFpbCI6ImphbWVzQG5pY2tqYW1lcy5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQzV1VPemhGeFdTeG5nY1NHd09qaVp1SncwSkFYNkYzNGtVWk9US3hUNGo4Nzc1LlZYTlJPSyJ9LCJpYXQiOjE2NjI4MTIxMDF9.qHTvafnmXOmJjw_71e3LhwKDQzIkosEMwCp6-ssUE7E"
 }